/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Actors
         * @description Hämta alla skådespelare med strukturerad response
         */
        get: operations["read_actors_actors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/{actor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Actor
         * @description Hämta specifik skådespelare med strukturerad response
         */
        get: operations["read_actor_actors__actor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/country/{country}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Actors By Country
         * @description Hämta skådespelare från specifikt land
         */
        get: operations["read_actors_by_country_actors_country__country__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/oscar-winners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Oscar Winners
         * @description Hämta endast Oscar-vinnare
         */
        get: operations["read_oscar_winners_actors_oscar_winners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Stats
         * @description Hämta statistik för skådespelare
         */
        get: operations["read_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Api Status
         * @description API status för frontend health check
         */
        get: operations["get_api_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * APIResponse
         * @description Standard API response för alla endpoints
         */
        APIResponse: {
            /**
             * Success
             * @description Indikerar om operationen lyckades
             * @example true
             */
            success: boolean;
            /**
             * Data
             * @description Response data (kan vara null vid fel)
             */
            data?: unknown;
            /**
             * Message
             * @description Beskrivande meddelande för användaren
             * @default
             * @example Operation completed successfully
             */
            message: string;
            /**
             * Error
             * @description Felmeddelande vid misslyckad operation
             * @example Resource not found
             */
            error?: string;
        };
        /**
         * Actor
         * @description Skådespelare med detaljerad information
         */
        Actor: {
            /**
             * Id
             * @description Unikt ID för skådespelaren
             * @example 1
             */
            id: number;
            /**
             * Name
             * @description Skådespelarens fullständiga namn
             * @example Meryl Streep
             */
            name: string;
            /**
             * Birth Year
             * @description Födelseår för skådespelaren
             * @example 1949
             */
            birth_year: number;
            /**
             * Country
             * @description Land där skådespelaren är född eller bor
             * @example USA
             */
            country: string;
            /**
             * Oscars
             * @description Antal Oscar-priser som skådespelaren har vunnit
             * @example 3
             */
            oscars: number;
        };
        /**
         * ActorListResponse
         * @description Response för lista av skådespelare
         */
        ActorListResponse: {
            /**
             * Success
             * @description Indikerar om operationen lyckades
             * @example true
             */
            success: boolean;
            /**
             * Data
             * @description Lista av skådespelare
             * @default []
             */
            data: components["schemas"]["Actor"][];
            /**
             * Total Count
             * @description Totalt antal skådespelare i listan
             * @example 5
             */
            total_count: number;
            /**
             * Message
             * @description Beskrivande meddelande
             * @default
             * @example Hittade 5 skådespelare
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * StatsResponse
         * @description Response för statistik-data
         */
        StatsResponse: {
            /**
             * Success
             * @description Indikerar om operationen lyckades
             * @example true
             */
            success: boolean;
            /**
             * Data
             * @description Statistik-data
             * @default {}
             * @example {
             *       "average_oscars": 3.2,
             *       "countries": [
             *         "USA",
             *         "Storbritannien",
             *         "Sverige"
             *       ],
             *       "total_actors": 5,
             *       "total_oscars": 16,
             *       "unique_countries": 3
             *     }
             */
            data: {
                [key: string]: unknown;
            };
            /**
             * Message
             * @description Beskrivande meddelande
             * @default
             * @example Statistik hämtad framgångsrikt
             */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_actors_actors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorListResponse"];
                };
            };
        };
    };
    read_actor_actors__actor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_actors_by_country_actors_country__country__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_oscar_winners_actors_oscar_winners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorListResponse"];
                };
            };
        };
    };
    read_stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    get_api_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
